#!/usr/bin/env python3
# pylint: disable=missing-module-docstring
# pylint: disable=missing-function-docstring
# pylint: disable=consider-using-f-string
# pylint: disable=invalid-name

import os
import sys
import textwrap
from argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument("--php-fpm", default="/usr/sbin/php-fpm8.1")
parser.add_argument("user")


def main(args):
    fpm_config = make_pipe(get_fpm_config(user=args.user))
    os.execvp(args.php_fpm, [args.php_fpm, "--nodaemonize", "--fpm-config", fpm_config])


def make_pipe(contents):
    r, w = os.pipe()
    contents = contents.encode()
    assert os.write(w, contents) == len(contents)
    os.close(w)
    os.set_inheritable(r, True)
    return "/dev/fd/%d" % r


def get_fpm_config(*, user):
    return textwrap.dedent(
        """\
            [%(user)s]
            user = %(user)s
            group = %(user)s
            listen = /run/php/%(user)s
            listen.owner = www-data
            listen.group = www-data
            pm = ondemand
            pm.process_idle_timeout = 10s
            pm.max_children = 30
            pm.max_requests = 500
            request_terminate_timeout = 600
            chdir = /
            security.limit_extensions = .php
            php_admin_value[error_log] = syslog
            php_admin_value[syslog.ident] = php %(user)s
        """
        % {"user": user}
    )


if __name__ == "__main__":
    sys.exit(main(parser.parse_args()))
